version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: minimal

shallow_clone: false

environment:
  PQCLEAN_ONLY_DIFF: 1
  matrix:
    - BITS: 64
    - BITS: 32

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"
    # Download AStyle 3.1: first enable strong crypto in Invoke-WebRequest
  - ps: Set-ItemProperty -Path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319" -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
  - ps: Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319" -Name "SchUseStrongCrypto" -Value '1' -Type DWord
    # Add Python to PATH
  - set PATH="C:\\Python37";"C:\\Python37\Scripts";%PATH%

build_script:
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch
  - git checkout %APPVEYOR_REPO_BRANCH%
  - git reset --hard %APPVEYOR_REPO_COMMIT%
  - python -m pip install -r requirements.txt
  - cd test
    # Download Astyle to local folder because putting it in PATH doesn't work
  - ps: Invoke-WebRequest -OutFile "astyle.exe" "https://rded.nl/pqclean/AStyle.exe"
    # Run tests
  - python -m nose -v --rednose
